### ISSUE TITLE
DC Estimation Inconvergence Check/Warnings

### ISSUE THREAD

**Issue by oguzhanogreden** [oguzhanogreden/mirt#13]
I'm not sure if this ever will be a problem but perhaps it's cheaper to check for this than risk it.

**Comment by philchalmers** [comment]
Thoughts on how to do this? Other than the second-order test of the observed information matrix, which I'll have to think about whether computing this is reasonable, this check is harder to do for EM algorithms.

**Comment by philchalmers** [comment]
I don't mind printing warning messages in the M-step, but I generally don't think this is required. All that matters in the M-step is that the complete-data log-likelihood (CD-LL) is higher at the end of the optimizer than at the initial optimizer location. Whether the optimizer converged or not is not itself that useful or important (in fact, with other optimizers I terminate the M-step early in the EM cycles knowing that very large jumps are being made because small convergence tol in the M-step is typically a waste of resources early on in the search). Perhaps checking whether the [initial CD-LL] <= [final CD-LL] would be sufficient?

**Comment by oguzhanogreden** [comment]
I'm not sure about how large the added benefit of checking initial vs final CD-LL would be. I can add this if you think it'd be useful.

**Comment by oguzhanogreden** [comment]
Done.
